version: '3.9'

services:
  postgres:
    image: postgres
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: pensions
      POSTGRES_USER: pensions
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local
